@startuml
skinparam usecase {
    BackgroundColor LightCyan
    BorderColor DarkSlateGray
}
skinparam packageStyle rectangle
left to right direction

actor "Gestor de Personal" as Gestor

package "Módulo de Gestión de Personal" {
    usecase "Registrar personal individual\ny asignar departamento" as UC_Gest1
    usecase "Carga masiva\n(Archivo plano)" as UC_Gest2
    usecase "Validar estructura\ne información" as UC_Gest3
    usecase "Actualizar estado del personal\n(otorgar/revocar/suspender)" as UC_Gest4
    usecase "Buscar personal\n(identificación, nombre,\napellido, departamento)" as UC_Gest5

    UC_Gest2 ..> UC_Gest3 : <<include>>
}

Gestor --> UC_Gest1
Gestor --> UC_Gest2
Gestor --> UC_Gest4
Gestor --> UC_Gest5
UC_Gest1 ..> UC_Login : <<include>>
UC_Gest2 ..> UC_Login : <<include>>
UC_Gest4 ..> UC_Login : <<include>>
UC_Gest5 ..> UC_Login : <<include>>

@enduml
