@startuml
skinparam usecase {
    BackgroundColor LightCyan
    BorderColor DarkSlateGray
}
skinparam packageStyle rectangle
left to right direction

actor "Supervisor / Auditor" as Sup #LightPink

package "Módulo de Reportes y Auditoría" {
    usecase "CU-08: Consultar historial por rango de fechas" as UC_Rep1
    usecase "CU-09: Generar documento descargable del historial" as UC_Rep2
    usecase "CU-10: Generar archivo periódico por departamentos" as UC_Rep3

    UC_Rep2 ..> UC_Rep1 : <<include>>
}

Sup --> UC_Rep1
Sup --> UC_Rep2
Sup --> UC_Rep3

note right of UC_Rep2
  Exporta el historial consultado
  a formato CSV o Excel.
end note

note right of UC_Rep3
  Agrupa accesos por departamento
  y genera archivo de intercambio
  para el Socio Internacional.
end note

@enduml
